// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ti-mo/comfo/rpc/comfo/service.proto

/*
Package comfo is a generated protocol buffer package.

It is generated from these files:
	github.com/ti-mo/comfo/rpc/comfo/service.proto

It has these top-level messages:
	Noop
	Bypass
	BootInfo
	Fans
	FanProfiles
	FanSpeedTarget
	FanSpeedModified
	Hours
	Temps
	FlushCacheRequest
	FlushCacheResponse
*/
package comfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Noop struct {
}

func (m *Noop) Reset()                    { *m = Noop{} }
func (m *Noop) String() string            { return proto.CompactTextString(m) }
func (*Noop) ProtoMessage()               {}
func (*Noop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Bypass struct {
	Factor     uint32 `protobuf:"varint,1,opt,name=Factor" json:"Factor,omitempty"`
	Level      uint32 `protobuf:"varint,2,opt,name=Level" json:"Level,omitempty"`
	Correction uint32 `protobuf:"varint,3,opt,name=Correction" json:"Correction,omitempty"`
	SummerMode bool   `protobuf:"varint,4,opt,name=SummerMode" json:"SummerMode,omitempty"`
}

func (m *Bypass) Reset()                    { *m = Bypass{} }
func (m *Bypass) String() string            { return proto.CompactTextString(m) }
func (*Bypass) ProtoMessage()               {}
func (*Bypass) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bypass) GetFactor() uint32 {
	if m != nil {
		return m.Factor
	}
	return 0
}

func (m *Bypass) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Bypass) GetCorrection() uint32 {
	if m != nil {
		return m.Correction
	}
	return 0
}

func (m *Bypass) GetSummerMode() bool {
	if m != nil {
		return m.SummerMode
	}
	return false
}

type BootInfo struct {
	MajorVersion uint32 `protobuf:"varint,1,opt,name=MajorVersion" json:"MajorVersion,omitempty"`
	MinorVersion uint32 `protobuf:"varint,2,opt,name=MinorVersion" json:"MinorVersion,omitempty"`
	BetaVersion  uint32 `protobuf:"varint,3,opt,name=BetaVersion" json:"BetaVersion,omitempty"`
	DeviceName   string `protobuf:"bytes,4,opt,name=DeviceName" json:"DeviceName,omitempty"`
}

func (m *BootInfo) Reset()                    { *m = BootInfo{} }
func (m *BootInfo) String() string            { return proto.CompactTextString(m) }
func (*BootInfo) ProtoMessage()               {}
func (*BootInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BootInfo) GetMajorVersion() uint32 {
	if m != nil {
		return m.MajorVersion
	}
	return 0
}

func (m *BootInfo) GetMinorVersion() uint32 {
	if m != nil {
		return m.MinorVersion
	}
	return 0
}

func (m *BootInfo) GetBetaVersion() uint32 {
	if m != nil {
		return m.BetaVersion
	}
	return 0
}

func (m *BootInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type Fans struct {
	InPercent  uint32 `protobuf:"varint,1,opt,name=InPercent" json:"InPercent,omitempty"`
	OutPercent uint32 `protobuf:"varint,2,opt,name=OutPercent" json:"OutPercent,omitempty"`
	InSpeed    uint32 `protobuf:"varint,3,opt,name=InSpeed" json:"InSpeed,omitempty"`
	OutSpeed   uint32 `protobuf:"varint,4,opt,name=OutSpeed" json:"OutSpeed,omitempty"`
}

func (m *Fans) Reset()                    { *m = Fans{} }
func (m *Fans) String() string            { return proto.CompactTextString(m) }
func (*Fans) ProtoMessage()               {}
func (*Fans) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Fans) GetInPercent() uint32 {
	if m != nil {
		return m.InPercent
	}
	return 0
}

func (m *Fans) GetOutPercent() uint32 {
	if m != nil {
		return m.OutPercent
	}
	return 0
}

func (m *Fans) GetInSpeed() uint32 {
	if m != nil {
		return m.InSpeed
	}
	return 0
}

func (m *Fans) GetOutSpeed() uint32 {
	if m != nil {
		return m.OutSpeed
	}
	return 0
}

type FanProfiles struct {
	OutAway      uint32 `protobuf:"varint,1,opt,name=OutAway" json:"OutAway,omitempty"`
	OutLow       uint32 `protobuf:"varint,2,opt,name=OutLow" json:"OutLow,omitempty"`
	OutMid       uint32 `protobuf:"varint,3,opt,name=OutMid" json:"OutMid,omitempty"`
	OutHigh      uint32 `protobuf:"varint,4,opt,name=OutHigh" json:"OutHigh,omitempty"`
	InFanActive  bool   `protobuf:"varint,5,opt,name=InFanActive" json:"InFanActive,omitempty"`
	InAway       uint32 `protobuf:"varint,6,opt,name=InAway" json:"InAway,omitempty"`
	InLow        uint32 `protobuf:"varint,7,opt,name=InLow" json:"InLow,omitempty"`
	InMid        uint32 `protobuf:"varint,8,opt,name=InMid" json:"InMid,omitempty"`
	InHigh       uint32 `protobuf:"varint,9,opt,name=InHigh" json:"InHigh,omitempty"`
	CurrentOut   uint32 `protobuf:"varint,10,opt,name=CurrentOut" json:"CurrentOut,omitempty"`
	CurrentIn    uint32 `protobuf:"varint,11,opt,name=CurrentIn" json:"CurrentIn,omitempty"`
	CurrentLevel uint32 `protobuf:"varint,12,opt,name=CurrentLevel" json:"CurrentLevel,omitempty"`
}

func (m *FanProfiles) Reset()                    { *m = FanProfiles{} }
func (m *FanProfiles) String() string            { return proto.CompactTextString(m) }
func (*FanProfiles) ProtoMessage()               {}
func (*FanProfiles) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FanProfiles) GetOutAway() uint32 {
	if m != nil {
		return m.OutAway
	}
	return 0
}

func (m *FanProfiles) GetOutLow() uint32 {
	if m != nil {
		return m.OutLow
	}
	return 0
}

func (m *FanProfiles) GetOutMid() uint32 {
	if m != nil {
		return m.OutMid
	}
	return 0
}

func (m *FanProfiles) GetOutHigh() uint32 {
	if m != nil {
		return m.OutHigh
	}
	return 0
}

func (m *FanProfiles) GetInFanActive() bool {
	if m != nil {
		return m.InFanActive
	}
	return false
}

func (m *FanProfiles) GetInAway() uint32 {
	if m != nil {
		return m.InAway
	}
	return 0
}

func (m *FanProfiles) GetInLow() uint32 {
	if m != nil {
		return m.InLow
	}
	return 0
}

func (m *FanProfiles) GetInMid() uint32 {
	if m != nil {
		return m.InMid
	}
	return 0
}

func (m *FanProfiles) GetInHigh() uint32 {
	if m != nil {
		return m.InHigh
	}
	return 0
}

func (m *FanProfiles) GetCurrentOut() uint32 {
	if m != nil {
		return m.CurrentOut
	}
	return 0
}

func (m *FanProfiles) GetCurrentIn() uint32 {
	if m != nil {
		return m.CurrentIn
	}
	return 0
}

func (m *FanProfiles) GetCurrentLevel() uint32 {
	if m != nil {
		return m.CurrentLevel
	}
	return 0
}

// Abs and Rel are mutually exclusive
type FanSpeedTarget struct {
	Abs uint32 `protobuf:"varint,1,opt,name=Abs" json:"Abs,omitempty"`
	Rel string `protobuf:"bytes,2,opt,name=Rel" json:"Rel,omitempty"`
}

func (m *FanSpeedTarget) Reset()                    { *m = FanSpeedTarget{} }
func (m *FanSpeedTarget) String() string            { return proto.CompactTextString(m) }
func (*FanSpeedTarget) ProtoMessage()               {}
func (*FanSpeedTarget) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FanSpeedTarget) GetAbs() uint32 {
	if m != nil {
		return m.Abs
	}
	return 0
}

func (m *FanSpeedTarget) GetRel() string {
	if m != nil {
		return m.Rel
	}
	return ""
}

type FanSpeedModified struct {
	Modified      bool   `protobuf:"varint,1,opt,name=Modified" json:"Modified,omitempty"`
	OriginalSpeed uint32 `protobuf:"varint,2,opt,name=OriginalSpeed" json:"OriginalSpeed,omitempty"`
	TargetSpeed   uint32 `protobuf:"varint,3,opt,name=TargetSpeed" json:"TargetSpeed,omitempty"`
	ReqTime       string `protobuf:"bytes,4,opt,name=ReqTime" json:"ReqTime,omitempty"`
}

func (m *FanSpeedModified) Reset()                    { *m = FanSpeedModified{} }
func (m *FanSpeedModified) String() string            { return proto.CompactTextString(m) }
func (*FanSpeedModified) ProtoMessage()               {}
func (*FanSpeedModified) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FanSpeedModified) GetModified() bool {
	if m != nil {
		return m.Modified
	}
	return false
}

func (m *FanSpeedModified) GetOriginalSpeed() uint32 {
	if m != nil {
		return m.OriginalSpeed
	}
	return 0
}

func (m *FanSpeedModified) GetTargetSpeed() uint32 {
	if m != nil {
		return m.TargetSpeed
	}
	return 0
}

func (m *FanSpeedModified) GetReqTime() string {
	if m != nil {
		return m.ReqTime
	}
	return ""
}

type Hours struct {
	FanAway      uint32 `protobuf:"varint,1,opt,name=FanAway" json:"FanAway,omitempty"`
	FanLow       uint32 `protobuf:"varint,2,opt,name=FanLow" json:"FanLow,omitempty"`
	FanMid       uint32 `protobuf:"varint,3,opt,name=FanMid" json:"FanMid,omitempty"`
	FanHigh      uint32 `protobuf:"varint,4,opt,name=FanHigh" json:"FanHigh,omitempty"`
	FrostProtect uint32 `protobuf:"varint,5,opt,name=FrostProtect" json:"FrostProtect,omitempty"`
	Reheating    uint32 `protobuf:"varint,6,opt,name=Reheating" json:"Reheating,omitempty"`
	BypassOpen   uint32 `protobuf:"varint,7,opt,name=BypassOpen" json:"BypassOpen,omitempty"`
	Filter       uint32 `protobuf:"varint,8,opt,name=Filter" json:"Filter,omitempty"`
}

func (m *Hours) Reset()                    { *m = Hours{} }
func (m *Hours) String() string            { return proto.CompactTextString(m) }
func (*Hours) ProtoMessage()               {}
func (*Hours) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Hours) GetFanAway() uint32 {
	if m != nil {
		return m.FanAway
	}
	return 0
}

func (m *Hours) GetFanLow() uint32 {
	if m != nil {
		return m.FanLow
	}
	return 0
}

func (m *Hours) GetFanMid() uint32 {
	if m != nil {
		return m.FanMid
	}
	return 0
}

func (m *Hours) GetFanHigh() uint32 {
	if m != nil {
		return m.FanHigh
	}
	return 0
}

func (m *Hours) GetFrostProtect() uint32 {
	if m != nil {
		return m.FrostProtect
	}
	return 0
}

func (m *Hours) GetReheating() uint32 {
	if m != nil {
		return m.Reheating
	}
	return 0
}

func (m *Hours) GetBypassOpen() uint32 {
	if m != nil {
		return m.BypassOpen
	}
	return 0
}

func (m *Hours) GetFilter() uint32 {
	if m != nil {
		return m.Filter
	}
	return 0
}

type Temps struct {
	Comfort     float32 `protobuf:"fixed32,1,opt,name=Comfort" json:"Comfort,omitempty"`
	OutsideAir  float32 `protobuf:"fixed32,2,opt,name=OutsideAir" json:"OutsideAir,omitempty"`
	SupplyAir   float32 `protobuf:"fixed32,3,opt,name=SupplyAir" json:"SupplyAir,omitempty"`
	OutAir      float32 `protobuf:"fixed32,4,opt,name=OutAir" json:"OutAir,omitempty"`
	ExhaustAir  float32 `protobuf:"fixed32,5,opt,name=ExhaustAir" json:"ExhaustAir,omitempty"`
	GeoHeat     float32 `protobuf:"fixed32,6,opt,name=GeoHeat" json:"GeoHeat,omitempty"`
	Reheating   float32 `protobuf:"fixed32,7,opt,name=Reheating" json:"Reheating,omitempty"`
	KitchenHood float32 `protobuf:"fixed32,8,opt,name=KitchenHood" json:"KitchenHood,omitempty"`
}

func (m *Temps) Reset()                    { *m = Temps{} }
func (m *Temps) String() string            { return proto.CompactTextString(m) }
func (*Temps) ProtoMessage()               {}
func (*Temps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Temps) GetComfort() float32 {
	if m != nil {
		return m.Comfort
	}
	return 0
}

func (m *Temps) GetOutsideAir() float32 {
	if m != nil {
		return m.OutsideAir
	}
	return 0
}

func (m *Temps) GetSupplyAir() float32 {
	if m != nil {
		return m.SupplyAir
	}
	return 0
}

func (m *Temps) GetOutAir() float32 {
	if m != nil {
		return m.OutAir
	}
	return 0
}

func (m *Temps) GetExhaustAir() float32 {
	if m != nil {
		return m.ExhaustAir
	}
	return 0
}

func (m *Temps) GetGeoHeat() float32 {
	if m != nil {
		return m.GeoHeat
	}
	return 0
}

func (m *Temps) GetReheating() float32 {
	if m != nil {
		return m.Reheating
	}
	return 0
}

func (m *Temps) GetKitchenHood() float32 {
	if m != nil {
		return m.KitchenHood
	}
	return 0
}

type FlushCacheRequest struct {
	// The type of cache to flush. One of all/fans/temps/profiles.
	Type string `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
}

func (m *FlushCacheRequest) Reset()                    { *m = FlushCacheRequest{} }
func (m *FlushCacheRequest) String() string            { return proto.CompactTextString(m) }
func (*FlushCacheRequest) ProtoMessage()               {}
func (*FlushCacheRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FlushCacheRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type FlushCacheResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	ReqTime string `protobuf:"bytes,2,opt,name=ReqTime" json:"ReqTime,omitempty"`
}

func (m *FlushCacheResponse) Reset()                    { *m = FlushCacheResponse{} }
func (m *FlushCacheResponse) String() string            { return proto.CompactTextString(m) }
func (*FlushCacheResponse) ProtoMessage()               {}
func (*FlushCacheResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FlushCacheResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *FlushCacheResponse) GetReqTime() string {
	if m != nil {
		return m.ReqTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Noop)(nil), "comfo.comfoserver.Noop")
	proto.RegisterType((*Bypass)(nil), "comfo.comfoserver.Bypass")
	proto.RegisterType((*BootInfo)(nil), "comfo.comfoserver.BootInfo")
	proto.RegisterType((*Fans)(nil), "comfo.comfoserver.Fans")
	proto.RegisterType((*FanProfiles)(nil), "comfo.comfoserver.FanProfiles")
	proto.RegisterType((*FanSpeedTarget)(nil), "comfo.comfoserver.FanSpeedTarget")
	proto.RegisterType((*FanSpeedModified)(nil), "comfo.comfoserver.FanSpeedModified")
	proto.RegisterType((*Hours)(nil), "comfo.comfoserver.Hours")
	proto.RegisterType((*Temps)(nil), "comfo.comfoserver.Temps")
	proto.RegisterType((*FlushCacheRequest)(nil), "comfo.comfoserver.FlushCacheRequest")
	proto.RegisterType((*FlushCacheResponse)(nil), "comfo.comfoserver.FlushCacheResponse")
}

func init() { proto.RegisterFile("github.com/ti-mo/comfo/rpc/comfo/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 855 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xd1, 0x6e, 0x23, 0x35,
	0x14, 0x55, 0xa6, 0x49, 0x9a, 0xdc, 0x6c, 0x57, 0xbb, 0x16, 0x82, 0x51, 0x85, 0x56, 0x65, 0x58,
	0xc4, 0xbe, 0x90, 0x4a, 0xc0, 0x1b, 0xe2, 0xa1, 0x2d, 0x64, 0x33, 0x62, 0xbb, 0xa9, 0x26, 0x05,
	0x09, 0xde, 0xdc, 0xe9, 0x6d, 0x62, 0x94, 0xd8, 0xb3, 0xb6, 0xa7, 0x4b, 0x78, 0xe2, 0x13, 0x78,
	0xe0, 0xc7, 0xf8, 0x08, 0x3e, 0x80, 0x3f, 0x40, 0xd7, 0xf6, 0x4c, 0x1c, 0x48, 0xd9, 0x97, 0xc8,
	0xe7, 0xdc, 0xeb, 0xeb, 0x33, 0xf7, 0x1e, 0x3b, 0x30, 0x5e, 0x08, 0xbb, 0xac, 0x6f, 0xc6, 0xa5,
	0x5a, 0x9f, 0x5a, 0xf1, 0xd9, 0x5a, 0x9d, 0x96, 0x6a, 0x7d, 0xa7, 0x4e, 0x75, 0x55, 0x86, 0x95,
	0x41, 0x7d, 0x2f, 0x4a, 0x1c, 0x57, 0x5a, 0x59, 0xc5, 0x9e, 0x3a, 0x72, 0xec, 0x7e, 0x29, 0x82,
	0x3a, 0xeb, 0x43, 0xf7, 0xb5, 0x52, 0x55, 0x76, 0x0f, 0xfd, 0xf3, 0x4d, 0xc5, 0x8d, 0x61, 0xef,
	0x43, 0x7f, 0xc2, 0x4b, 0xab, 0x74, 0xda, 0x39, 0xe9, 0xbc, 0x38, 0x2a, 0x02, 0x62, 0xef, 0x41,
	0xef, 0x15, 0xde, 0xe3, 0x2a, 0x4d, 0x1c, 0xed, 0x01, 0x7b, 0x06, 0x70, 0xa1, 0xb4, 0xc6, 0xd2,
	0x0a, 0x25, 0xd3, 0x03, 0x17, 0x8a, 0x18, 0x8a, 0xcf, 0xeb, 0xf5, 0x1a, 0xf5, 0xa5, 0xba, 0xc5,
	0xb4, 0x7b, 0xd2, 0x79, 0x31, 0x28, 0x22, 0x26, 0xfb, 0xa3, 0x03, 0x83, 0x73, 0xa5, 0x6c, 0x2e,
	0xef, 0x14, 0xcb, 0xe0, 0xd1, 0x25, 0xff, 0x59, 0xe9, 0x1f, 0x50, 0x1b, 0x2a, 0xe7, 0x05, 0xec,
	0x70, 0x2e, 0x47, 0xc8, 0x6d, 0x4e, 0x12, 0x72, 0x22, 0x8e, 0x9d, 0xc0, 0xe8, 0x1c, 0x2d, 0x6f,
	0x52, 0xbc, 0xaa, 0x98, 0x22, 0x59, 0xdf, 0x20, 0x75, 0xe6, 0x35, 0x5f, 0x7b, 0x59, 0xc3, 0x22,
	0x62, 0xb2, 0x5f, 0xa1, 0x3b, 0xe1, 0xd2, 0xb0, 0x0f, 0x61, 0x98, 0xcb, 0x2b, 0xd4, 0x25, 0x4a,
	0x1b, 0xe4, 0x6c, 0x09, 0xaa, 0x32, 0xab, 0x6d, 0x13, 0xf6, 0x4a, 0x22, 0x86, 0xa5, 0x70, 0x98,
	0xcb, 0x79, 0x85, 0x78, 0x1b, 0x34, 0x34, 0x90, 0x1d, 0xc3, 0x60, 0x56, 0x5b, 0x1f, 0xea, 0xba,
	0x50, 0x8b, 0xb3, 0x3f, 0x13, 0x18, 0x4d, 0xb8, 0xbc, 0xd2, 0xea, 0x4e, 0xac, 0xd0, 0x50, 0x95,
	0x59, 0x6d, 0xcf, 0xde, 0xf2, 0x4d, 0x50, 0xd0, 0x40, 0x1a, 0xd5, 0xac, 0xb6, 0xaf, 0xd4, 0xdb,
	0x70, 0x76, 0x40, 0x81, 0xbf, 0x14, 0xcd, 0xb1, 0x01, 0x85, 0x4a, 0x53, 0xb1, 0x58, 0x86, 0x43,
	0x1b, 0x48, 0x1d, 0xcb, 0xe5, 0x84, 0xcb, 0xb3, 0xd2, 0x8a, 0x7b, 0x4c, 0x7b, 0x6e, 0x4e, 0x31,
	0x45, 0x35, 0x73, 0xe9, 0x44, 0xf4, 0x7d, 0x4d, 0x8f, 0xc8, 0x16, 0xb9, 0x24, 0x09, 0x87, 0xde,
	0x16, 0x0e, 0x78, 0x96, 0x04, 0x0c, 0x1a, 0x96, 0xce, 0x77, 0x35, 0xdc, 0xf1, 0xc3, 0xa6, 0x86,
	0x3b, 0x9d, 0x4c, 0x54, 0x6b, 0x8d, 0xd2, 0xce, 0x6a, 0x9b, 0x42, 0x30, 0x51, 0xcb, 0xd0, 0x14,
	0x02, 0xca, 0x65, 0x3a, 0xf2, 0x53, 0x68, 0x09, 0x72, 0x44, 0x00, 0xde, 0x9f, 0x8f, 0xbc, 0x23,
	0x62, 0x2e, 0xfb, 0x12, 0x1e, 0x4f, 0xb8, 0xef, 0xfd, 0x35, 0xd7, 0x0b, 0xb4, 0xec, 0x09, 0x1c,
	0x9c, 0xdd, 0x98, 0xd0, 0x51, 0x5a, 0x12, 0x53, 0x04, 0x7b, 0x0f, 0x0b, 0x5a, 0x66, 0xbf, 0x77,
	0xe0, 0x49, 0xb3, 0xed, 0x52, 0xdd, 0x8a, 0x3b, 0xe1, 0x47, 0xd7, 0xac, 0xdd, 0xee, 0x41, 0xd1,
	0x62, 0xf6, 0x1c, 0x8e, 0x66, 0x5a, 0x2c, 0x84, 0xe4, 0x2b, 0x3f, 0x5b, 0x3f, 0x97, 0x5d, 0x92,
	0x9a, 0xed, 0x45, 0xc4, 0xd6, 0x88, 0x29, 0x1a, 0x54, 0x81, 0x6f, 0xae, 0x45, 0xeb, 0xcd, 0x06,
	0x66, 0x7f, 0x75, 0xa0, 0x37, 0x55, 0xb5, 0x76, 0xb6, 0xa0, 0xe9, 0x44, 0xb6, 0x08, 0xd0, 0xdf,
	0x60, 0x19, 0xd9, 0xc2, 0xa3, 0xc0, 0x47, 0xb6, 0xf0, 0x28, 0x54, 0x8a, 0x6d, 0x11, 0x20, 0xb5,
	0x76, 0xa2, 0x95, 0xb1, 0x57, 0x5a, 0x59, 0x2c, 0xad, 0xf3, 0xc5, 0x51, 0xb1, 0xc3, 0xd1, 0x70,
	0x0a, 0x5c, 0x22, 0xb7, 0x42, 0x2e, 0x82, 0x37, 0xb6, 0x04, 0x8d, 0xd6, 0xbf, 0x2b, 0xb3, 0x0a,
	0x65, 0xf0, 0x48, 0xc4, 0x38, 0x4d, 0x62, 0x65, 0x51, 0x07, 0xa7, 0x04, 0x94, 0xfd, 0xdd, 0x81,
	0xde, 0x35, 0xae, 0x2b, 0xf7, 0x9d, 0x17, 0xf4, 0x60, 0x69, 0x7f, 0x01, 0x93, 0xa2, 0x81, 0xe1,
	0xfa, 0x19, 0x71, 0x8b, 0x67, 0x42, 0xbb, 0x6f, 0x4d, 0x8a, 0x88, 0x21, 0x65, 0xf3, 0xba, 0xaa,
	0x56, 0x1b, 0x0a, 0x1f, 0xb8, 0xf0, 0x96, 0x08, 0x97, 0x84, 0x42, 0x5d, 0x17, 0x0a, 0x88, 0xaa,
	0x7e, 0xfb, 0xcb, 0x92, 0xd7, 0xc6, 0xc5, 0x7a, 0xbe, 0xea, 0x96, 0x21, 0x3d, 0x2f, 0x51, 0x4d,
	0x91, 0x5b, 0xf7, 0xb5, 0x49, 0xd1, 0xc0, 0xdd, 0x4e, 0x1c, 0xfa, 0xf3, 0xb6, 0x9d, 0x38, 0x81,
	0xd1, 0x77, 0xc2, 0x96, 0x4b, 0x94, 0x53, 0xa5, 0xfc, 0xc5, 0x48, 0x8a, 0x98, 0xca, 0x3e, 0x85,
	0xa7, 0x93, 0x55, 0x6d, 0x96, 0x17, 0xbc, 0x5c, 0x62, 0x81, 0x6f, 0x6a, 0x34, 0x96, 0x31, 0xe8,
	0x5e, 0x6f, 0x2a, 0x74, 0xdf, 0x3e, 0x2c, 0xdc, 0x3a, 0x9b, 0x02, 0x8b, 0x13, 0x4d, 0xa5, 0xa4,
	0x41, 0x12, 0x36, 0xaf, 0xcb, 0x12, 0x8d, 0x09, 0xbe, 0x6c, 0x60, 0x6c, 0xa7, 0x64, 0xc7, 0x4e,
	0x9f, 0xff, 0x76, 0x00, 0x3d, 0xd7, 0x4e, 0xf6, 0x35, 0x0c, 0x5e, 0xa2, 0xf5, 0x2d, 0xff, 0x60,
	0xfc, 0x9f, 0x3f, 0x8a, 0x31, 0xfd, 0x4b, 0x1c, 0xa7, 0x7b, 0x02, 0x7e, 0xcb, 0x57, 0xd4, 0x15,
	0xeb, 0xde, 0xcc, 0x07, 0x77, 0xef, 0x0b, 0xb8, 0x1d, 0x39, 0x3c, 0xf6, 0x9b, 0xdb, 0x37, 0xef,
	0xc1, 0x1a, 0xcf, 0xf6, 0xd7, 0x68, 0x37, 0x7e, 0x0f, 0xa3, 0xb9, 0x2b, 0xe5, 0x2f, 0xd2, 0x47,
	0xfb, 0xd3, 0xa3, 0x87, 0xe0, 0xf8, 0xe3, 0xff, 0x49, 0x69, 0x2f, 0xf6, 0x8f, 0x00, 0xdb, 0x8e,
	0xb3, 0xe7, 0xfb, 0xb6, 0xfc, 0x7b, 0x72, 0xc7, 0x9f, 0xbc, 0x23, 0xcb, 0x8f, 0xed, 0xfc, 0xf0,
	0xa7, 0x9e, 0xcb, 0xb8, 0xe9, 0xbb, 0x3f, 0xe9, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x31,
	0x53, 0x1d, 0x8c, 0xd6, 0x07, 0x00, 0x00,
}
